### ISSUE TITLE
Contribution and Code of Conduct Guide: Creating a Contribution and Code of Conduct Guide for new comers

### ISSUE THREAD

**Issue by Ansalpandey** [Tezosaitclub/BlockchainClubWebsite#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Tezosaitclub** [comment]
@Ansalpandey You can start working on it.

**Comment by Tezosaitclub** [comment]
Successfully  merged the changes, no conflicts found.
